FROM typesense/typesense:30.1

COPY data/typesense/data /data/

RUN chmod -R 755 /data

EXPOSE 8108

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["/opt/typesense-server --data-dir=/data --api-key=\"${TYPESENSE_API_KEY}\" --enable-cors"]
