FROM node:current-alpine3.23 AS base
WORKDIR /app
EXPOSE 4321

FROM base AS production
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build
CMD ["node", "dist/server/entry.mjs"]

FROM base AS development
COPY package*.json ./
RUN npm ci
COPY . .
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
